import { useState, useMemo, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Plus, X, ChevronRight, ChevronDown, Wand2, Trash2, FileJson, Layers, Lock, Users, UserPlus, ArrowLeft, ChevronLeft, ChevronRightIcon, Pencil, Save, Image as ImageIcon, Type, XCircle, UploadCloud } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogFooter
} from "@/components/ui/dialog";
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { cn } from "@/lib/utils";
import { useApp } from "@/context/AppContext";

// --- Types ---

type EntryNodeType = 'category' | 'subject';
type FormMode = 'template' | 'entry';

interface TemplateNode {
    id: string;
    type: EntryNodeType;
    name: string;
    maxMarks?: string; // Only for subjects
    children?: TemplateNode[];
    isOpen?: boolean;
}

interface StudentEntry {
    id: string;
    name: string;
    fatherName: string;
    rollNo: string;
    className: string;
    customFields: { id: string; key: string; value: string }[];
    // Key = subject ID, Value = marks obtained
    marks: Record<string, string>;
}

interface SavedTemplate {
    id: string;
    name: string;
    timestamp: number;
    structure: TemplateNode[];
    examTitle: string;
    headerImage?: string | null;
    footerText?: string;
}

interface ManualEntryFormProps {
    onGenerate: (data: unknown) => void;
    onCancel: () => void;
}

// --- Utils ---

const generateId = () => Math.random().toString(36).substr(2, 9);

// --- Components ---

export function ManualEntryForm({ onGenerate, onCancel }: ManualEntryFormProps) {
    // --- State ---
    const [mode, setMode] = useState<FormMode>('template');

    // Template State (Structure Definition)
    const [template, setTemplate] = useState<TemplateNode[]>([
        {
            id: generateId(),
            type: 'category',
            name: 'Objective',
            isOpen: true,
            children: [
                { id: generateId(), type: 'subject', name: 'Mathematics', maxMarks: '100' },
                { id: generateId(), type: 'subject', name: 'Science', maxMarks: '100' }
            ]
        },
        {
            id: generateId(),
            type: 'category',
            name: 'Subjective',
            isOpen: true,
            children: [
                { id: generateId(), type: 'subject', name: 'Art Education', maxMarks: '100' }
            ]
        }
    ]);

    // Students State (Data Entries)
    const [students, setStudents] = useState<StudentEntry[]>([
        { id: generateId(), name: '', fatherName: '', rollNo: '', className: '', customFields: [], marks: {} }
    ]);
    const [currentStudentIndex, setCurrentStudentIndex] = useState(0);

    // Filter/Save State
    const [savedTemplates, setSavedTemplates] = useState<SavedTemplate[]>([]);

    useEffect(() => {
        const saved = localStorage.getItem('reportMaker_templates');
        if (saved) {
            try {
                setSavedTemplates(JSON.parse(saved));
            } catch (e) {
                console.error("Failed to parse saved templates");
            }
        }
    }, []);

    const saveTemplatesToStorage = (newTemplates: SavedTemplate[]) => {
        setSavedTemplates(newTemplates);
        localStorage.setItem('reportMaker_templates', JSON.stringify(newTemplates));
    };


    const confirmDeleteTemplate = () => {
        if (templateToDelete) {
            const newTemplates = savedTemplates.filter(t => t.id !== templateToDelete);
            saveTemplatesToStorage(newTemplates);
            setTemplateToDelete(null);
        }
    };

    const confirmLoadTemplate = () => {
        if (templateToLoad) {
            setTemplate(templateToLoad.structure);
            setExamTitle(templateToLoad.examTitle || '');
            setReportHeader(templateToLoad.headerImage || null);
            setReportFooter(templateToLoad.footerText || 'Generated by MG Global School AI Engine');
            setIsTemplateLoaded(true); // Mark as loaded from saved
            setTemplateToLoad(null);
        }
    };

    const [previewMode, setPreviewMode] = useState(false);

    // Dialog States
    const [isSaveDialogOpen, setIsSaveDialogOpen] = useState(false);
    const [templateNameInput, setTemplateNameInput] = useState('');
    const [alertMessage, setAlertMessage] = useState<string | null>(null);
    const [templateToDelete, setTemplateToDelete] = useState<string | null>(null);
    const [templateToLoad, setTemplateToLoad] = useState<SavedTemplate | null>(null);
    const [isTemplateLoaded, setIsTemplateLoaded] = useState(false);

    // --- Derived State ---
    const currentStudent = students[currentStudentIndex];

    // Flatten template to get all subject IDs for marks entry
    const allSubjects = useMemo(() => {
        const subjects: { id: string; name: string; maxMarks: string; category: string }[] = [];
        const traverse = (nodes: TemplateNode[], parentCategory: string = '') => {
            nodes.forEach(node => {
                if (node.type === 'subject') {
                    subjects.push({ id: node.id, name: node.name, maxMarks: node.maxMarks || '100', category: parentCategory });
                } else if (node.children) {
                    traverse(node.children, node.name);
                }
            });
        };
        traverse(template);
        return subjects;
    }, [template]);

    // --- Handlers: Template ---

    const updateTemplateNode = (nodes: TemplateNode[], targetId: string, updater: (node: TemplateNode) => TemplateNode): TemplateNode[] => {
        return nodes.map(node => {
            if (node.id === targetId) return updater(node);
            if (node.children) return { ...node, children: updateTemplateNode(node.children, targetId, updater) };
            return node;
        });
    };

    const deleteTemplateNode = (nodes: TemplateNode[], targetId: string): TemplateNode[] => {
        return nodes
            .filter(node => node.id !== targetId)
            .map(node => ({
                ...node,
                children: node.children ? deleteTemplateNode(node.children, targetId) : undefined
            }));
    };

    const addTemplateNode = (nodes: TemplateNode[], parentId: string | null, newNode: TemplateNode): TemplateNode[] => {
        if (parentId === null) return [...nodes, newNode];
        return nodes.map(node => {
            if (node.id === parentId) {
                return { ...node, children: [...(node.children || []), newNode], isOpen: true };
            }
            if (node.children) return { ...node, children: addTemplateNode(node.children, parentId, newNode) };
            return node;
        });
    };

    const handleUpdateTemplateNode = (id: string, field: keyof TemplateNode, value: unknown) => {
        setTemplate(prev => updateTemplateNode(prev, id, n => ({ ...n, [field]: value })));
    };

    const handleDeleteTemplateNode = (id: string) => {
        setTemplate(prev => deleteTemplateNode(prev, id));
    };

    const handleAddTemplateChild = (parentId: string | null, type: EntryNodeType) => {
        const newNode: TemplateNode = type === 'category'
            ? { id: generateId(), type: 'category', name: 'New Category', children: [], isOpen: true }
            : { id: generateId(), type: 'subject', name: 'New Subject', maxMarks: '100' };

        setTemplate(prev => addTemplateNode(prev, parentId, newNode));
    };

    // --- Handlers: Students ---

    const updateCurrentStudent = (field: keyof StudentEntry, value: unknown) => {
        setStudents(prev => prev.map((s, i) => i === currentStudentIndex ? { ...s, [field]: value } : s));
    };

    const updateStudentMark = (subjectId: string, marks: string) => {
        setStudents(prev => prev.map((s, i) =>
            i === currentStudentIndex
                ? { ...s, marks: { ...s.marks, [subjectId]: marks } }
                : s
        ));
    };

    const addCustomField = () => {
        setStudents(prev => prev.map((s, i) =>
            i === currentStudentIndex
                ? { ...s, customFields: [...s.customFields, { id: generateId(), key: '', value: '' }] }
                : s
        ));
    };

    const updateCustomField = (fieldId: string, fieldKey: 'key' | 'value', text: string) => {
        setStudents(prev => prev.map((s, i) =>
            i === currentStudentIndex
                ? { ...s, customFields: s.customFields.map(f => f.id === fieldId ? { ...f, [fieldKey]: text } : f) }
                : s
        ));
    };

    const removeCustomField = (fieldId: string) => {
        setStudents(prev => prev.map((s, i) =>
            i === currentStudentIndex
                ? { ...s, customFields: s.customFields.filter(f => f.id !== fieldId) }
                : s
        ));
    };

    const addNewStudent = () => {
        const newStudent: StudentEntry = { id: generateId(), name: '', fatherName: '', rollNo: '', className: '', customFields: [], marks: {} };
        setStudents(prev => [...prev, newStudent]);
        setCurrentStudentIndex(students.length); // Navigate to the new student
    };

    const removeStudent = (index: number) => {
        if (students.length <= 1) return; // Keep at least one
        setStudents(prev => prev.filter((_, i) => i !== index));
        if (currentStudentIndex >= index && currentStudentIndex > 0) {
            setCurrentStudentIndex(currentStudentIndex - 1);
        }
    };

    // --- Mode Transition ---

    const lockTemplate = () => {
        if (allSubjects.length === 0) {
            setAlertMessage('Please add at least one subject to the template before proceeding.');
            return;
        }

        // If template was loaded from saved, skip save dialog and go directly to entry mode
        if (isTemplateLoaded) {
            setMode('entry');
            return;
        }

        // Open Save Dialog for new templates
        setTemplateNameInput(examTitle || '');
        setIsSaveDialogOpen(true);
    };

    const handleSaveAndLock = () => {
        const nameToSave = templateNameInput.trim() || examTitle || "Untitled Template";
        const newTemplate: SavedTemplate = {
            id: generateId(),
            name: nameToSave,
            timestamp: Date.now(),
            structure: template,
            examTitle: examTitle,
            headerImage: reportHeader.imageData,
            footerText: reportFooter.text
        };
        saveTemplatesToStorage([...savedTemplates, newTemplate]);

        setIsSaveDialogOpen(false);
        setMode('entry');
    };

    const handleSkipAndLock = () => {
        setIsSaveDialogOpen(false);
        setMode('entry');
    };



    const editTemplate = () => {
        setMode('template');
    };

    // --- Format Output ---

    const formatOutput = () => {
        // Convert each student to a flat structure for the AI
        return students.map(student => {
            const processNode = (node: TemplateNode): unknown => {
                if (node.type === 'subject') {
                    return {
                        name: node.name,
                        marks: student.marks[node.id] || '',
                        maxMarks: node.maxMarks
                    };
                }
                const childrenObj: Record<string, unknown> = {};
                let categoryTotalMax = 0;

                node.children?.forEach(child => {
                    const childResult = processNode(child) as any;
                    childrenObj[child.name] = childResult;

                    // Accumulate max marks for immediate children if they are subjects
                    // Note: This simple accumulation works for 1-level deep categories. 
                    // For nested categories, you'd need recursive summing, but let's keep it robust.
                    if (child.type === 'subject') {
                        categoryTotalMax += Number(child.maxMarks) || 0;
                    } else if (child.type === 'category' && childResult.totalMaxMarks) {
                        categoryTotalMax += Number(childResult.totalMaxMarks) || 0;
                    }
                });

                // Inject totalMaxMarks into the output object for the category
                childrenObj['totalMaxMarks'] = categoryTotalMax;
                return childrenObj;
            };

            const academicObj: Record<string, unknown> = {};
            template.forEach(node => {
                const result = processNode(node) as any;
                academicObj[node.name] = result;
            });

            return {
                studentProfile: {
                    name: student.name,
                    fatherName: student.fatherName,
                    rollNo: student.rollNo,
                    Class: student.className,
                    ...student.customFields.reduce((acc, curr) => ({ ...acc, [curr.key]: curr.value }), {})
                },
                academicPerformance: academicObj
            };
        });
    };

    const handleSubmit = () => {
        const data = formatOutput();
        onGenerate(data);
    };

    // --- Render Helpers ---

    const renderTemplateNode = (node: TemplateNode, level: number = 0) => {
        const isCategory = node.type === 'category';

        return (
            <div key={node.id} className={cn("relative transition-all", level > 0 && "ml-4 md:ml-6")}>
                {level > 0 && (
                    <div className="absolute -left-4 md:-left-6 top-6 w-3 md:w-5 h-px bg-white/20" />
                )}
                {level > 0 && (
                    <div className="absolute -left-4 md:-left-6 -top-1 bottom-0 w-px bg-white/20" />
                )}

                <div className={cn(
                    "flex flex-col md:flex-row gap-3 mb-3 p-3 rounded-xl border group items-start md:items-center transition-all hover:bg-white/5",
                    isCategory ? "bg-white/5 border-white/10" : "bg-transparent border-white/5"
                )}>
                    {isCategory && (
                        <button
                            onClick={() => handleUpdateTemplateNode(node.id, 'isOpen', !node.isOpen)}
                            className="p-1.5 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition-colors hidden md:block"
                        >
                            {node.isOpen ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                        </button>
                    )}

                    <div className="flex items-center gap-3 flex-1 w-full">
                        {isCategory ? (
                            <Layers className="w-4 h-4 text-purple-400 shrink-0" />
                        ) : (
                            <div className="w-4 h-4 rounded-full border-2 border-slate-600 shrink-0" />
                        )}
                        <Input
                            value={node.name}
                            onChange={(e) => handleUpdateTemplateNode(node.id, 'name', e.target.value)}
                            className="h-9 font-medium bg-transparent border-transparent hover:border-white/20 focus:border-purple-500 text-white placeholder:text-slate-600 flex-1 min-w-[120px] transition-all"
                            placeholder={isCategory ? "Category Name" : "Subject Name"}
                        />
                    </div>

                    {!isCategory && (
                        <div className="flex items-center gap-2 w-full md:w-auto">
                            <div className="flex items-center bg-slate-900/50 rounded-lg border border-white/10 overflow-hidden px-2">
                                <span className="text-slate-500 text-xs">Max:</span>
                                <Input
                                    value={node.maxMarks}
                                    onChange={(e) => handleUpdateTemplateNode(node.id, 'maxMarks', e.target.value)}
                                    className="h-9 w-20 md:w-24 text-center border-none bg-transparent text-slate-300 focus-visible:ring-0 placeholder:text-slate-600"
                                    placeholder="100"
                                />
                            </div>
                        </div>
                    )}

                    {isCategory && (
                        <div className="flex items-center bg-white/5 rounded-lg border border-white/5 px-3 py-1.5 h-9">
                            <span className="text-slate-500 text-xs uppercase tracking-wider mr-2">Total Max:</span>
                            <span className="text-emerald-400 text-sm font-semibold">
                                {(() => {
                                    const calculateTotalMax = (n: TemplateNode): number => {
                                        if (n.type === 'subject') return Number(n.maxMarks) || 0;
                                        return (n.children || []).reduce((acc, child) => acc + calculateTotalMax(child), 0);
                                    };
                                    const total = calculateTotalMax(node);
                                    return total > 0 ? total : '—';
                                })()}
                            </span>
                        </div>
                    )}

                    <div className="flex items-center gap-1 opacity-100 md:opacity-0 group-hover:opacity-100 transition-opacity self-end md:self-auto">
                        {isCategory && (
                            <>
                                <Button size="icon" variant="ghost" className="h-8 w-8 text-slate-400 hover:text-white hover:bg-white/10" onClick={() => handleAddTemplateChild(node.id, 'subject')} title="Add Subject">
                                    <Plus className="w-4 h-4" />
                                </Button>
                                <Button size="icon" variant="ghost" className="h-8 w-8 text-slate-400 hover:text-white hover:bg-white/10" onClick={() => handleAddTemplateChild(node.id, 'category')} title="Add Sub-Category">
                                    <Layers className="w-4 h-4" />
                                </Button>
                                <Separator orientation="vertical" className="h-4 mx-1 bg-white/10" />
                            </>
                        )}
                        <Button
                            size="icon"
                            variant="ghost"
                            className="h-8 w-8 text-slate-500 hover:text-red-400 hover:bg-red-500/10"
                            onClick={() => handleDeleteTemplateNode(node.id)}
                            title="Remove"
                        >
                            <Trash2 className="w-4 h-4" />
                        </Button>
                    </div>
                </div>

                {isCategory && node.isOpen && node.children && (
                    <div className="flex flex-col border-l border-white/5 ml-[19px] md:ml-[22px]">
                        {node.children.map(child => renderTemplateNode(child, level + 1))}
                    </div>
                )}
            </div>
        );
    };



    // --- Handlers: Branding ---
    const { examTitle, setExamTitle, reportHeader, setReportHeader, reportFooter, setReportFooter } = useApp();
    const [isDragging, setIsDragging] = useState(false);

    const handleImageUpload = (file: File) => {
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (e) => {
            const img = new Image();
            img.onload = () => {
                const canvas = document.createElement('canvas');
                const ctx = canvas.getContext('2d');
                const maxWidth = 3000;

                let width = img.width;
                let height = img.height;

                if (width > maxWidth) {
                    height = (height * maxWidth) / width;
                    width = maxWidth;
                }

                canvas.width = width;
                canvas.height = height;
                ctx?.drawImage(img, 0, 0, width, height);

                const compressedBase64 = canvas.toDataURL('image/jpeg', 0.8);
                setReportHeader(compressedBase64);
            };
            img.src = e.target?.result as string;
        };
        reader.readAsDataURL(file);
    };

    const onDrop = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(false);
        const file = e.dataTransfer.files[0];
        if (file && file.type.startsWith('image/')) {
            handleImageUpload(file);
        }
    };

    // --- Main Render ---

    return (
        <div className="max-w-6xl mx-auto p-4 md:p-6 lg:p-8 text-white">


            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
                <div>
                    <h2 className="text-3xl font-bold text-white tracking-tight">Manual Entry</h2>
                    <p className="text-slate-400 mt-1">
                        {mode === 'template'
                            ? 'Step 1: Define the report card structure (subjects & max marks).'
                            : `Step 2: Enter student data (${students.length} student${students.length > 1 ? 's' : ''}).`}
                    </p>
                </div>
                <div className="flex gap-3 w-full md:w-auto">
                    <Button variant={previewMode ? "secondary" : "ghost"} onClick={() => setPreviewMode(!previewMode)} className="text-slate-300 hover:text-white hover:bg-white/10 border border-white/10">
                        <FileJson className="w-4 h-4 mr-2" />
                        {previewMode ? "Hide JSON" : "Show JSON"}
                    </Button>
                    <Button variant="outline" onClick={onCancel} className="bg-transparent border-white/10 text-slate-300 hover:bg-white/5 hover:text-white">Cancel</Button>

                    {mode === 'template' ? (
                        <Button onClick={lockTemplate} className="bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white shadow-lg shadow-emerald-500/20 border border-white/10">
                            <Lock className="w-4 h-4 mr-2" />
                            Lock Template & Enter Data
                        </Button>
                    ) : (
                        <Button onClick={handleSubmit} className="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white shadow-lg shadow-purple-500/20 border border-white/10">
                            <Wand2 className="w-4 h-4 mr-2" />
                            Generate {students.length} Report{students.length > 1 ? 's' : ''}
                        </Button>
                    )}
                </div>
            </div>

            {/* Mode-Specific Content */}
            <AnimatePresence mode="wait">
                {mode === 'template' ? (
                    <motion.div key="template-mode" initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 20 }} className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
                        {/* Left Column: Info/Preview */}
                        <div className="space-y-6 lg:col-span-1">
                            <Card className="bg-emerald-500/10 border-emerald-500/30 shadow-lg">
                                <CardHeader className="pb-3">
                                    <CardTitle className="text-lg text-emerald-300 flex items-center gap-2"><Layers className="w-5 h-5" /> Template Mode</CardTitle>
                                </CardHeader>
                                <CardContent className="text-sm text-slate-300">
                                    <p>Define the structure of your report card here. Add categories (like "Scholastic Areas") and subjects under them.</p>
                                    <p className="mt-2 text-slate-400">Once locked, you will be prompted to save this template for future use.</p>
                                </CardContent>
                            </Card>

                            {/* Saved Templates List */}
                            {savedTemplates.length > 0 && (
                                <Card className="bg-white/5 border-white/10 shadow-lg max-h-[400px] overflow-hidden flex flex-col">
                                    <CardHeader className="pb-3 border-b border-white/5 bg-white/5">
                                        <CardTitle className="text-sm text-slate-300 flex items-center gap-2 uppercase tracking-wider font-bold">
                                            <Save className="w-4 h-4 text-purple-400" /> Saved Templates
                                        </CardTitle>
                                    </CardHeader>
                                    <CardContent className="p-0 overflow-y-auto flex-1">
                                        <div className="divide-y divide-white/5">
                                            {savedTemplates.map(t => (
                                                <div key={t.id} className="p-3 hover:bg-white/5 transition-colors group flex items-start gap-3">
                                                    <div
                                                        onClick={() => setTemplateToLoad(t)}
                                                        className="flex-1 cursor-pointer"
                                                    >
                                                        <h4 className="text-sm font-medium text-purple-200 group-hover:text-purple-100 mb-0.5">{t.name}</h4>
                                                        <div className="flex items-center gap-2 text-[10px] text-slate-500">
                                                            <span>{new Date(t.timestamp).toLocaleDateString()}</span>
                                                            <span>•</span>
                                                            <span>{t.examTitle || 'No Title'}</span>
                                                        </div>
                                                    </div>
                                                    <Button
                                                        size="icon"
                                                        variant="ghost"
                                                        className="h-7 w-7 text-slate-600 hover:text-red-400 hover:bg-red-500/10 opacity-0 group-hover:opacity-100 transition-all"
                                                        onClick={() => setTemplateToDelete(t.id)}
                                                    >
                                                        <Trash2 className="w-3.5 h-3.5" />
                                                    </Button>
                                                </div>
                                            ))}
                                        </div>
                                    </CardContent>
                                </Card>
                            )}

                            {previewMode && (
                                <Card className="bg-black/40 border-white/10 text-slate-300 overflow-hidden backdrop-blur-md">
                                    <CardHeader className="pb-2 border-b border-white/5">
                                        <CardTitle className="text-sm font-mono text-purple-400">Template Structure</CardTitle>
                                    </CardHeader>
                                    <CardContent className="p-4">
                                        <pre className="text-xs font-mono overflow-auto max-h-[300px] text-green-400/80">
                                            {JSON.stringify(template, null, 2)}
                                        </pre>
                                    </CardContent>
                                </Card>
                            )}
                        </div>

                        {/* Right Column: Template Builder */}
                        <div className="lg:col-span-2 space-y-6">
                            <div className="w-full max-w-4xl bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl relative overflow-hidden">
                                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500"></div>



                                <Card className="bg-white/5 backdrop-blur-xl border-white/10 shadow-2xl min-h-[500px] flex flex-col">
                                    <CardHeader className="border-b border-white/10 pb-4 sticky top-0 z-10 bg-[#0f172a]/95 backdrop-blur-xl rounded-t-xl">
                                        <div className="flex justify-between items-center">
                                            <div className="flex-1 mr-4">
                                                <div className="group relative inline-block max-w-full">
                                                    <input
                                                        type="text"
                                                        value={examTitle}
                                                        onChange={(e) => setExamTitle(e.target.value)}
                                                        className="bg-transparent text-lg md:text-xl font-bold text-white uppercase tracking-tight focus:outline-none focus:ring-1 focus:ring-purple-500/50 rounded px-2 py-1 w-full border border-transparent hover:border-white/10 transition-colors"
                                                        placeholder="Enter Exam Title..."
                                                    />
                                                    <Pencil className="w-3 h-3 text-slate-500 group-hover:text-purple-400 opacity-0 group-hover:opacity-100 transition-all absolute top-1/2 -translate-y-1/2 -right-4" />
                                                </div>
                                                <CardDescription className="text-slate-400 mt-1">Build the hierarchy of subjects and max marks for this exam.</CardDescription>
                                            </div>
                                            <Button size="sm" onClick={() => handleAddTemplateChild(null, 'category')} className="gap-2 bg-white/10 hover:bg-white/20 text-white border border-white/10">
                                                <Plus className="w-4 h-4" /> Root Category
                                            </Button>
                                        </div>
                                    </CardHeader>
                                    <CardContent className="p-6 flex-1 relative">
                                        <div className="space-y-1">
                                            {template.map(node => renderTemplateNode(node))}
                                        </div>

                                        {template.length === 0 && (
                                            <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-500">
                                                <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center mb-4">
                                                    <Layers className="w-8 h-8 opacity-40" />
                                                </div>
                                                <p className="text-lg font-medium text-slate-400">Structure is empty</p>
                                                <p className="text-sm opacity-60 mb-6">Start by adding a main category (e.g., "Objective")</p>
                                                <Button onClick={() => handleAddTemplateChild(null, 'category')} className="bg-purple-600/20 hover:bg-purple-600/30 text-purple-300 hover:text-purple-200 border border-purple-500/30">
                                                    <Plus className="w-4 h-4 mr-2" />
                                                    Add Objective Section
                                                </Button>
                                            </div>
                                        )}
                                    </CardContent>
                                </Card>
                            </div>

                            {/* Branding Studio Card */}
                            <div className="w-full max-w-4xl bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl relative overflow-hidden mt-8">
                                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-pink-500 via-rose-500 to-orange-500"></div>
                                <div className="flex flex-col gap-6">
                                    <div className="flex items-center gap-3 mb-2">
                                        <div className="p-2 bg-pink-500/10 rounded-lg">
                                            <Wand2 className="w-6 h-6 text-pink-400" />
                                        </div>
                                        <div>
                                            <h3 className="text-xl font-bold text-white">Branding Studio</h3>
                                            <p className="text-sm text-slate-400">Customize the look of your reports.</p>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        {/* Header Image Uploader */}
                                        <div className="space-y-3">
                                            <Label className="text-slate-300 flex items-center gap-2">
                                                <ImageIcon className="w-4 h-4 text-purple-400" /> Header Image
                                            </Label>

                                            <div
                                                className={cn(
                                                    "border-2 border-dashed rounded-xl p-6 transition-all duration-300 relative group min-h-[160px] flex flex-col items-center justify-center text-center",
                                                    isDragging ? "border-pink-500 bg-pink-500/10 scale-[1.02]" : "border-white/10 bg-white/5 hover:border-pink-500/30 hover:bg-white/10",
                                                    reportHeader.imageData ? "border-solid border-purple-500/30" : ""
                                                )}
                                                onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                                                onDragLeave={() => setIsDragging(false)}
                                                onDrop={onDrop}
                                            >
                                                {reportHeader.imageData ? (
                                                    <div className="w-full relative group/image">
                                                        <img src={reportHeader.imageData} alt="Header Preview" className="w-full h-24 object-cover rounded-lg shadow-lg border border-white/10" />
                                                        <div className="absolute inset-0 bg-black/60 opacity-0 group-hover/image:opacity-100 transition-opacity flex items-center justify-center gap-2 rounded-lg backdrop-blur-sm">
                                                            <Button
                                                                size="sm"
                                                                variant="destructive"
                                                                onClick={(e) => {
                                                                    e.stopPropagation();
                                                                    setReportHeader(null);
                                                                }}
                                                                className="h-8 px-3"
                                                            >
                                                                <Trash2 className="w-3 h-3 mr-2" /> Remove
                                                            </Button>
                                                        </div>
                                                        <p className="text-xs text-green-400 mt-2 font-medium flex items-center justify-center gap-1">
                                                            <UploadCloud className="w-3 h-3" /> Image Active
                                                        </p>
                                                    </div>
                                                ) : (
                                                    <>
                                                        <input
                                                            type="file"
                                                            accept="image/*"
                                                            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                                                            onChange={(e) => {
                                                                if (e.target.files?.[0]) handleImageUpload(e.target.files[0]);
                                                            }}
                                                        />
                                                        <div className="flex flex-col items-center gap-3">
                                                            <div className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center group-hover:scale-110 transition-transform">
                                                                <UploadCloud className="w-5 h-5 text-slate-400 group-hover:text-pink-400 transition-colors" />
                                                            </div>
                                                            <div className="space-y-1">
                                                                <p className="text-sm font-medium text-slate-300 group-hover:text-white transition-colors">
                                                                    Drag & Drop Header
                                                                </p>
                                                                <p className="text-xs text-slate-500">
                                                                    or click to browse
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </>
                                                )}
                                            </div>
                                        </div>

                                        {/* Footer Text Editor */}
                                        <div className="space-y-3">
                                            <Label className="text-slate-300 flex items-center gap-2">
                                                <Type className="w-4 h-4 text-purple-400" /> Footer Text
                                            </Label>
                                            <div className="relative">
                                                <Input
                                                    value={reportFooter.text}
                                                    onChange={(e) => setReportFooter(e.target.value)}
                                                    className="bg-white/5 border-white/10 text-white pl-4 pr-10 focus:ring-pink-500/50"
                                                    placeholder="Enter custom footer text..."
                                                />
                                                {reportFooter.text !== 'Generated by MG Global School AI Engine' && (
                                                    <Button
                                                        size="icon"
                                                        variant="ghost"
                                                        className="absolute right-1 top-1 h-7 w-7 text-slate-400 hover:text-white"
                                                        onClick={() => setReportFooter('Generated by MG Global School AI Engine')}
                                                        title="Reset to default"
                                                    >
                                                        <XCircle className="w-4 h-4" />
                                                    </Button>
                                                )}
                                            </div>

                                            {/* Mini Live Preview */}
                                            <div className="mt-4 p-4 rounded-xl bg-white border border-slate-200 shadow-sm opacity-90">
                                                <p className="text-[10px] text-slate-400 uppercase tracking-widest font-bold mb-2">Print Preview</p>
                                                <div className="h-2 w-full bg-slate-100 rounded mb-2"></div>
                                                <div className="h-2 w-3/4 bg-slate-100 rounded mb-4"></div>
                                                <div className="flex justify-between items-end border-t border-slate-200 pt-2 mt-2">
                                                    <span className="text-[8px] text-slate-400">Page 1 of 1</span>
                                                    <span className="text-[8px] font-medium text-slate-600 truncate max-w-[150px]">
                                                        {reportFooter.text}
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                ) : (
                    <motion.div key="entry-mode" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
                        {/* Left Column: Student List & Profile */}
                        <div className="space-y-6 lg:col-span-1">
                            {/* Edit Template Link */}
                            <Button variant="ghost" onClick={editTemplate} className="text-slate-400 hover:text-white text-sm p-0 h-auto">
                                <ArrowLeft className="w-4 h-4 mr-2" /> Edit Template
                            </Button>

                            {/* Student List */}
                            <Card className="bg-white/5 backdrop-blur-xl border-white/10 shadow-2xl">
                                <CardHeader className="border-b border-white/10 pb-3">
                                    <div className="flex justify-between items-center">
                                        <CardTitle className="text-lg text-white flex items-center gap-2"><Users className="w-5 h-5 text-purple-400" /> Students</CardTitle>
                                        <Button size="sm" onClick={addNewStudent} className="gap-1.5 bg-purple-600/20 hover:bg-purple-600/30 text-purple-300 border border-purple-500/30 h-8">
                                            <UserPlus className="w-3 h-3" /> Add
                                        </Button>
                                    </div>
                                </CardHeader>
                                <CardContent className="p-3 max-h-[200px] overflow-y-auto">
                                    <div className="space-y-1">
                                        {students.map((s, idx) => (
                                            <div
                                                key={s.id}
                                                onClick={() => setCurrentStudentIndex(idx)}
                                                className={cn(
                                                    "flex items-center justify-between p-2 rounded-lg cursor-pointer transition-all group",
                                                    idx === currentStudentIndex ? "bg-purple-500/20 border border-purple-500/40" : "hover:bg-white/5 border border-transparent"
                                                )}
                                            >
                                                <span className="text-sm text-white truncate flex-1">{s.name || `Student ${idx + 1}`}</span>
                                                {students.length > 1 && (
                                                    <Button size="icon" variant="ghost" className="h-6 w-6 opacity-0 group-hover:opacity-100 text-red-400 hover:bg-red-500/20" onClick={(e) => { e.stopPropagation(); removeStudent(idx); }}>
                                                        <Trash2 className="w-3 h-3" />
                                                    </Button>
                                                )}
                                            </div>
                                        ))}
                                    </div>
                                </CardContent>
                            </Card>

                            {/* Student Profile Form */}
                            <Card className="bg-white/5 backdrop-blur-xl border-white/10 shadow-2xl">
                                <CardHeader className="border-b border-white/10 pb-4">
                                    <CardTitle className="text-lg text-white">Student Profile</CardTitle>
                                    <CardDescription className="text-slate-400">Details for {currentStudent?.name || `Student ${currentStudentIndex + 1}`}</CardDescription>
                                </CardHeader>
                                <CardContent className="space-y-4 pt-5">
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                        <div className="space-y-2">
                                            <Label className="text-slate-300">Student Name</Label>
                                            <Input placeholder="e.g. John Doe" value={currentStudent?.name || ''} onChange={(e) => updateCurrentStudent('name', e.target.value)} className="bg-slate-900/50 border-white/10 text-white" />
                                        </div>
                                        <div className="space-y-2">
                                            <Label className="text-slate-300">Father's Name</Label>
                                            <Input placeholder="e.g. Robert Doe" value={currentStudent?.fatherName || ''} onChange={(e) => updateCurrentStudent('fatherName', e.target.value)} className="bg-slate-900/50 border-white/10 text-white" />
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="space-y-2">
                                            <Label className="text-slate-300">Roll No.</Label>
                                            <Input placeholder="e.g. 101" value={currentStudent?.rollNo || ''} onChange={(e) => updateCurrentStudent('rollNo', e.target.value)} className="bg-slate-900/50 border-white/10 text-white" />
                                        </div>
                                        <div className="space-y-2">
                                            <Label className="text-slate-300">Class</Label>
                                            <Input placeholder="e.g. 10th" value={currentStudent?.className || ''} onChange={(e) => updateCurrentStudent('className', e.target.value)} className="bg-slate-900/50 border-white/10 text-white" />
                                        </div>
                                    </div>
                                    <Separator className="bg-white/10" />
                                    <div className="space-y-3">
                                        <div className="flex items-center justify-between">
                                            <Label className="text-slate-400">Custom Attributes</Label>
                                            <Button size="sm" variant="ghost" onClick={addCustomField} className="h-6 px-2 text-xs text-purple-400 hover:text-purple-300 hover:bg-purple-500/10">
                                                <Plus className="w-3 h-3 mr-1" /> Add
                                            </Button>
                                        </div>
                                        <AnimatePresence>
                                            {currentStudent?.customFields.map(field => (
                                                <motion.div key={field.id} initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="flex gap-2 items-center">
                                                    <Input className="h-8 text-xs bg-slate-900/50 border-white/10 text-white" placeholder="Key" value={field.key} onChange={(e) => updateCustomField(field.id, 'key', e.target.value)} />
                                                    <Input className="h-8 text-xs bg-slate-900/50 border-white/10 text-white" placeholder="Value" value={field.value} onChange={(e) => updateCustomField(field.id, 'value', e.target.value)} />
                                                    <Button size="icon" variant="ghost" className="h-8 w-8 text-slate-500 hover:text-red-400" onClick={() => removeCustomField(field.id)}>
                                                        <X className="w-3 h-3" />
                                                    </Button>
                                                </motion.div>
                                            ))}
                                        </AnimatePresence>
                                    </div>
                                </CardContent>
                            </Card>

                            {previewMode && (
                                <Card className="bg-black/40 border-white/10">
                                    <CardHeader className="pb-2 border-b border-white/5"><CardTitle className="text-sm font-mono text-purple-400">All Students Payload</CardTitle></CardHeader>
                                    <CardContent className="p-4"><pre className="text-xs font-mono overflow-auto max-h-[200px] text-green-400/80">{JSON.stringify(formatOutput(), null, 2)}</pre></CardContent>
                                </Card>
                            )}
                        </div>

                        {/* Right Column: Marks Entry Grid */}
                        <div className="lg:col-span-2 space-y-6">
                            <div className="w-full max-w-4xl bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl relative overflow-hidden">
                                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 via-pink-500 to-orange-500"></div>

                                <div className="flex items-center justify-between mb-6">
                                    <h3 className="text-xl font-bold text-white">Marks Entry</h3>
                                    <div className="flex items-center gap-2">
                                        <Button size="icon" variant="ghost" disabled={currentStudentIndex === 0} onClick={() => setCurrentStudentIndex(i => i - 1)} className="h-8 w-8 text-slate-400 hover:text-white disabled:opacity-30">
                                            <ChevronLeft className="w-5 h-5" />
                                        </Button>
                                        <span className="text-sm text-slate-400 px-2">{currentStudentIndex + 1} / {students.length}</span>
                                        <Button size="icon" variant="ghost" disabled={currentStudentIndex === students.length - 1} onClick={() => setCurrentStudentIndex(i => i + 1)} className="h-8 w-8 text-slate-400 hover:text-white disabled:opacity-30">
                                            <ChevronRightIcon className="w-5 h-5" />
                                        </Button>
                                    </div>
                                </div>

                                <div className="space-y-4">
                                    {/* Group Subjects by Category */}
                                    {template.map(category => (
                                        <Card key={category.id} className="bg-white/5 border-white/10">
                                            <CardHeader className="py-3 px-4 border-b border-white/5">
                                                <CardTitle className="text-sm text-slate-400 uppercase tracking-wider">{category.name}</CardTitle>
                                            </CardHeader>
                                            <CardContent className="p-4 space-y-4">
                                                {/* Recursive rendering for nested structures */}
                                                {(() => {
                                                    const renderDataEntryFields = (node: TemplateNode, depth = 0) => {
                                                        if (node.type === 'subject') {
                                                            return (
                                                                <div key={node.id} className="flex items-center gap-3 bg-slate-900/50 rounded-lg p-3 border border-white/5">
                                                                    <Label className="flex-1 text-white text-sm font-medium pl-1">{node.name}</Label>
                                                                    <div className="flex items-center bg-slate-800 rounded-md border border-white/10 overflow-hidden shrink-0">
                                                                        <Input
                                                                            value={currentStudent?.marks[node.id] || ''}
                                                                            onChange={(e) => {
                                                                                const val = e.target.value;
                                                                                const max = node.maxMarks === 'Grade' ? null : Number(node.maxMarks);

                                                                                // Validation: If it's a number, ensure it doesn't exceed maxMarks
                                                                                if (max !== null && val !== '' && !isNaN(Number(val))) {
                                                                                    if (Number(val) > max) {
                                                                                        // Prevent update or show error? The user said "not be possible", so we block.
                                                                                        return;
                                                                                    }
                                                                                }
                                                                                updateStudentMark(node.id, val);
                                                                            }}
                                                                            className={cn(
                                                                                "h-9 w-16 text-center border-none bg-transparent text-white focus-visible:ring-0",
                                                                                // Visual cue if accidentally invalid (though blocked)
                                                                            )}
                                                                            placeholder="—"
                                                                        />
                                                                        <span className="text-slate-500 text-xs px-2 border-l border-white/10">/ {node.maxMarks}</span>
                                                                    </div>
                                                                </div>
                                                            );
                                                        }

                                                        // Categories
                                                        if (!node.children || node.children.length === 0) return null;

                                                        return (
                                                            <div key={node.id} className={cn("space-y-3", depth > 0 && "pl-4 border-l border-white/5 mt-2")}>
                                                                {depth > 0 && <h4 className="text-xs text-slate-400 font-semibold uppercase">{node.name}</h4>}
                                                                <div className={cn("grid gap-4", depth === 0 ? "grid-cols-1 sm:grid-cols-2" : "grid-cols-1")}>
                                                                    {node.children.map(child => renderDataEntryFields(child, depth + 1))}
                                                                </div>
                                                            </div>
                                                        );
                                                    };

                                                    // If the root is a category, we start processing its children
                                                    // This handles the top-level card content
                                                    if (category.children) {
                                                        return (
                                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                                                {category.children.map(child => renderDataEntryFields(child, 0))}
                                                            </div>
                                                        );
                                                    }
                                                    return null;
                                                })()}
                                            </CardContent>
                                        </Card>
                                    ))}
                                </div>

                                {/* Quick Navigation Buttons */}
                                <div className="flex justify-end gap-3 mt-8 pt-6 border-t border-white/10">
                                    {currentStudentIndex < students.length - 1 ? (
                                        <Button onClick={() => setCurrentStudentIndex(i => i + 1)} className="bg-white/10 hover:bg-white/20 text-white">
                                            Next Student <ChevronRightIcon className="w-4 h-4 ml-2" />
                                        </Button>
                                    ) : (
                                        <Button onClick={addNewStudent} className="bg-white/10 hover:bg-white/20 text-white">
                                            <UserPlus className="w-4 h-4 mr-2" /> Add Another Student
                                        </Button>
                                    )}
                                </div>
                            </div>
                        </div>
                    </motion.div>
                )}
                {/* Save Template Dialog */}
                <Dialog open={isSaveDialogOpen} onOpenChange={setIsSaveDialogOpen}>
                    <DialogContent className="bg-slate-900 border-white/10 text-white sm:max-w-md">
                        <DialogHeader>
                            <DialogTitle>Save Template</DialogTitle>
                            <DialogDescription className="text-slate-400">
                                Would you like to save this template structure for future use?
                            </DialogDescription>
                        </DialogHeader>
                        <div className="py-4">
                            <Label htmlFor="templateName" className="text-slate-300 mb-2 block">Template Name</Label>
                            <Input
                                id="templateName"
                                value={templateNameInput}
                                onChange={(e) => setTemplateNameInput(e.target.value)}
                                placeholder="e.g., Term 1 Report card"
                                className="bg-slate-950 border-white/10 text-white"
                            />
                        </div>
                        <DialogFooter className="flex gap-2 sm:justify-between">
                            <Button variant="ghost" onClick={handleSkipAndLock} className="text-slate-400 hover:text-white hover:bg-white/10">
                                Don't Save
                            </Button>
                            <Button onClick={handleSaveAndLock} className="bg-purple-600 hover:bg-purple-700 text-white">
                                Save & Continue
                            </Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>

                {/* Generic Alert Dialog */}
                <Dialog open={!!alertMessage} onOpenChange={(open) => !open && setAlertMessage(null)}>
                    <DialogContent className="bg-slate-900 border-white/10 text-white sm:max-w-md">
                        <DialogHeader>
                            <DialogTitle className="text-red-400 flex items-center gap-2">
                                Note
                            </DialogTitle>
                            <DialogDescription className="text-slate-300 pt-2">
                                {alertMessage}
                            </DialogDescription>
                        </DialogHeader>
                        <DialogFooter>
                            <Button onClick={() => setAlertMessage(null)} className="bg-white/10 hover:bg-white/20 text-white">
                                Close
                            </Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
                {/* Delete Confirmation Alert */}
                <AlertDialog open={!!templateToDelete} onOpenChange={(open) => !open && setTemplateToDelete(null)}>
                    <AlertDialogContent className="bg-slate-900 border-white/10 text-white">
                        <AlertDialogHeader>
                            <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                            <AlertDialogDescription className="text-slate-400">
                                This action cannot be undone. This will permanently delete the saved template.
                            </AlertDialogDescription>
                        </AlertDialogHeader>
                        <AlertDialogFooter>
                            <AlertDialogCancel className="bg-white/5 border-white/10 text-slate-300 hover:bg-white/10 hover:text-white" onClick={() => setTemplateToDelete(null)}>Cancel</AlertDialogCancel>
                            <AlertDialogAction className="bg-red-600 hover:bg-red-700 text-white border-none" onClick={confirmDeleteTemplate}>Delete</AlertDialogAction>
                        </AlertDialogFooter>
                    </AlertDialogContent>
                </AlertDialog>

                {/* Load Confirmation Alert */}
                <AlertDialog open={!!templateToLoad} onOpenChange={(open) => !open && setTemplateToLoad(null)}>
                    <AlertDialogContent className="bg-slate-900 border-white/10 text-white">
                        <AlertDialogHeader>
                            <AlertDialogTitle>Load Template?</AlertDialogTitle>
                            <AlertDialogDescription className="text-slate-400">
                                Loading this template will overwrite any unsaved changes in your current template structure.
                            </AlertDialogDescription>
                        </AlertDialogHeader>
                        <AlertDialogFooter>
                            <AlertDialogCancel className="bg-white/5 border-white/10 text-slate-300 hover:bg-white/10 hover:text-white" onClick={() => setTemplateToLoad(null)}>Cancel</AlertDialogCancel>
                            <AlertDialogAction className="bg-purple-600 hover:bg-purple-700 text-white border-none" onClick={confirmLoadTemplate}>Load Template</AlertDialogAction>
                        </AlertDialogFooter>
                    </AlertDialogContent>
                </AlertDialog>
            </AnimatePresence>
        </div>
    );
}
